# Generated by Django 4.2.5 on 2023-12-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_category_products_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
    ]
